"""
Week 10 reference: build this together with your instructor.

Goal: add sound effects, background music, and an on-screen score to
the gem-collecting mechanic from Weeks 6-7, using shared/sound.py and
pygame's font module.

The sound files in assets/ are simple placeholder tones, generated by
code rather than recorded or downloaded -- good enough to learn with.
Swap in your own sound effects and music any time you like.
"""

import sys
from pathlib import Path

import pygame

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "shared"))
from input_handler import get_movement_vector
from physics import check_collision
from sound import play_music, play_sound

pygame.init()

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("Week 10: Sound & Score")

clock = pygame.time.Clock()

ASSETS_DIR = Path(__file__).resolve().parent / "assets"
gem_image = pygame.image.load(ASSETS_DIR / "gem.png").convert_alpha()

# TALK: pygame.font.Font(None, size) uses pygame's built-in default
# font. Passing a .ttf file path instead of None would use a custom
# font -- worth exploring later, but not required this week.
score_font = pygame.font.Font(None, 48)

BACKGROUND_COLOR = (20, 20, 40)
PLAYER_COLOR = (240, 120, 60)
PLAYER_SIZE = 40
PLAYER_SPEED = 5
POINTS_PER_GEM = 10

player_rect = pygame.Rect(50, 50, PLAYER_SIZE, PLAYER_SIZE)

gem_positions = [(150, 150), (400, 100), (650, 200), (200, 450), (600, 400)]
gems = []
for x, y in gem_positions:
    gems.append({"rect": gem_image.get_rect(center=(x, y)), "collected": False})

score = 0

# TODO (together): start background music, looping forever.
play_music(str(ASSETS_DIR / "music.wav"), volume=0.25)

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # --- UPDATE ---
    dx, dy = get_movement_vector()
    player_rect.x += dx * PLAYER_SPEED
    player_rect.y += dy * PLAYER_SPEED
    player_rect.clamp_ip(screen.get_rect())

    for gem in gems:
        if not gem["collected"] and check_collision(player_rect, gem["rect"]):
            gem["collected"] = True
            score += POINTS_PER_GEM
            # TODO (together): play a sound effect right when a gem is
            # collected -- this only runs the frame collection happens,
            # same as the score increase right above it.
            play_sound(str(ASSETS_DIR / "collect.wav"), volume=0.6)

    # --- DRAW ---
    screen.fill(BACKGROUND_COLOR)

    for gem in gems:
        if not gem["collected"]:
            screen.blit(gem_image, gem["rect"])

    pygame.draw.rect(screen, PLAYER_COLOR, player_rect)

    # TODO (together): render the score as text and blit it in a
    # corner of the screen.
    # TALK: render() builds a brand-new Surface out of text every time
    # it's called -- that's why we call it fresh each frame, right
    # before drawing it, instead of once at the very start.
    score_surface = score_font.render(f"Score: {score}", True, (255, 255, 255))
    screen.blit(score_surface, (10, 10))

    pygame.display.flip()
    clock.tick(60)

pygame.quit()
